---
title: "Chapter 1 Suggested Problems"
format: html
---

## Suggested Problems

1. Show that a vector space over $\mathbf{C}$ of dimension $n$ can be thought of as a vector space over $\mathbf{R}$ of dimension $2n$. 

2. Let $V$ be the set of infinite sequences $(a_1,a_2,\ldots)$ where $a_{i}\in\mathbf{R}$ for all $i$ and all but finitely many of the $a_{i}$ are zero.  Show that $V$ is a real vector space
and that the set of vectors $e_{i}$ having a one in position $i$ and zeroes elsewhere (for all $i=1,2,\ldots$) is a basis for $V$.

3. Look at the proof of the result that every vector space has a basis.  We established this by
using Zorn's lemma to prove that there is a maximal linearly independent set, and that this set is a basis.  You can instead consider spanning sets, which are partially ordered in the "opposite" direction.  Use Zorn's lemma to show that there is a minimal spanning set, and that this must be a basis. 

4. Study each of the following system of equations and describe their solutions.
A.
$$
\begin{aligned}
x + y + z &= 6\\
2x - y + z &= 3\\
x + 2y - z &= 2
\end{aligned}
$$

B. 
$$
\begin{aligned}
x + y + z &= 6\\
x + 2y + z &= 9\\
5x + 8y + 5z &= 39
\end{aligned}
$$

C. 
$$
\begin{aligned}
x + y + z &= 1\\
x  + z &= 3\\
x - y + z &= 0
\end{aligned}
$$