---
title: Vector Spaces, subspaces, dimension
---

\newcommand{\R}{\mathbf{R}}
\newcommand{\F}{\mathbf{F}}
\newcommand{\C}{\mathbf{C}}

### Real and Complex Vectors

An $n$-dimensional real vector is an $n$-tuple $(x_1,\ldots, x_n)$ where the $x_i$ are real numbers.
If the $x_i$ are complex instead of real, we have an $n$-dimensional complex vector.

We write $\R^{n}$ and $\C^{n}$ for the sets of $n$-dimensional real and complex vectors respectively.

One can visualize an element $x=(x_1,\ldots,x_n)$ of $\R^{n}$ as an "arrow" with its base at the origin and its endpoint at the point $(x_1,\ldots, x_n)$ in $n$-dimensional Euclidean space. 

Elements of $\R$ or $\C$ are often called *scalars*.

### Operations

The set $\R^{n}$ allows for:

**Addition of vectors.**  If 

$$x=(x_1,\ldots, x_n)\in R^{n} (or \C^{n})$$ and 

$$y=(y_1,\ldots, y_n)\in\R^{n} (or \C^{n})$$

then 
$$x+y=(x_1+y_1,\dots, x_n+y_n)$$
 is in $\R^{n}$ (or $\C^{n}$).


**Multiplication of a vector by a scalar.**  If 
$$a\in\R\ \mathrm{and}\  y=(y_1,\ldots, y_n)\in\R^{n}$$

 then $ay=(ay_1,\ldots, ay_n)$.  Similarly if $a\in\C$
and $y\in\C^{n}$. 


### Axioms

These operations satisfy a list of axioms.  For simplicity let's work with $\R$ and $\R^{n}$ but the same things are true for $\R^{n}$ and $\C^{n}$.

1. Vector addition is commutative, associative, and if $e=(0,\ldots,0)$
then $x+e=e+x=x$.
2. Scalar multiplication distributes over addition so that
$(a+b)x=ax+bx$ and $a(x+y)=ax+ay$.
3. Scalar multiplication is "associative" in the sense that $a(bx)=(ab)x$.
4. $1x=x$ and $0x=e$.

### Real (and Complex) Vector spaces

**Definition:** A *vector space* over $\R$ is a set $V$ together with two operations:
- Addition.  Given $x,y$ in $V$, there is an element $x+y\in V$.
- Scalar Multiplication.  Given $a\in\R$ and $x\in V$ there is an element $ax\in V$.

The two operations must satisfy the axioms listed above.  In particular there must be an element $e\in V$ so that $x+e=e+x=x$ for all $x\in V$. 

A vector space over $\C$ is the same except that scalar multiplication is defined for $a\in \C$, not just $\R$.

The spaces $\R^{n}$ and $\C^{n}$ above are examples of real and complex vector spaces
respectively.

### Subspaces

**Definition:** A subspace $W$ of a vector space $V$ (for either $\R$ or $\C$) is a subset of $V$ that is a vector space under the inherited operations from $V$.

**Example:** Consider the set $W$ of vectors $(x_1,x_2,0)$ inside $\R^{3}$.  This is a 
copy of $\R^{2}$ sitting inside $\R^{3}$ so it's a subspace.  

**Example:** Let $W$ be the set of vectors in $\R^{n}$ that satisfy $x_1+x_2+\cdots+x_n=0$. This is a subspace. Check:
- If $u=(u_1,\ldots, u_n)$ and $v=(v_1,\ldots, v_n)$ are in $W$, then 
$u+v$ is in $W$ because 

$$(u_1+v_1)+\cdots+(u_n+v_n)=(u_1+\cdots u_n)+(v_1+\cdots v_n)=0$$

Similarly $au_1+au_2+\cdots+au_n=a(u_1+\cdots u_n)=0$ so $au$ is in $W$.

Finally $e=(0,\ldots,0)$ is in $W$.

The other axioms hold for elements of $W$ since all elements of $W$ are also elements of $V$.

**Example** Let $W$ be the set of vectors in $\R^{n}$ that satisfy $x_1+\cdots+x_n=1$.
This is **NOT** a subspace.

**Proposition:** A subset $W$ of $V$ is a subspace provided that it contains the element $e$
and whenever $u,v\in W$ it follows that $u+v\in W$ and $au\in W$ for all $a\in\R$.

You can replace $\R$ by $\C$ in the above to obtain the same results for complex vector spaces.


### Four Crucial Definitions

#### Span of a set of vectors

**Definition:** Let $V$ be a vector space and let $S=\{v_1,\ldots, v_k\}$ be a set of vectors in $V$.  The **span** of $S$ is defined as either of the following equivalent things:

1.  The set of all vectors $\sum_{i=1}^{n} a_i v_i$ as $(a_1,\ldots, a_n)$ runs over $\R^{n}$. 

2.  The intersection of all subspaces of $V$ that contain $S$.

The set $H$ in 1 is a subspace that contains $S$. If $W$ is the intersection of all subspaces containing $S$, then $W\subset H$ since $H$ is among the sets being intersected.  On the other hand, since $S$ is contained in $W$, and $W$ is a subspace,
the elements in $H$ are also in $W$.  So $W=H$.

#### Linear Independence

**Definition:** A set of vectors $v_1,\ldots, v_n$ in a vector space $V$ is *linearly independent*
if the only solution $(a_1,\ldots, a_n)$ to the equation

$$
\sum_{i=1}^{n} a_i v_i=0
$$

is $(0,\ldots, 0)$.

Equivalently:

- a set $S=\{v_1,\ldots, v_n\}$ is linearly independent if the span of any proper subset of $S$ is a proper subspace of the span of $S$.

Suppose 
$$
\sum a_{i}v_{i}=0
$$
and that $a_{j}\not=0$.  Then you can "solve"
for $v_{j}$ in terms of the other vectors:
$$
v_{j}=-\sum_{i\not=j} a_{i}/a_{j} v_{i}
$$
so $v_{j}$ is in the span of the remaining $v_{i}$.  Thus the span of the set $S\backslash\{v_{j}\}$ is the same as the span of $S$.  

Conversely, if there is a proper subset $U$ of $S$ whose span equals $V$, choose $v_{i}\not\in U$.  Since $v_{i}$ is in the span of $U$, you can write
$$
v_{i} = \sum_{v_{j}\in U} b_{j}v_{j} 
$$ 
and therefore 
$$
-v_{i}+\sum b_{j}v_{j}=0
$$
and so $S$ is not linearly independent. 

- a set $S=\{v_1,\ldots, v_n\}$ is not linearly independent (is *dependent*) if and only if
there is some $1\le j\le n$ such that
$$
v_{j}=\sum_{\substack{i=1 \\ i \neq j}}^{n} a_{i}v_{i}
$$

This is implicit in the argument above. 

#### Basis

A set $S$ of vectors in a vector space $V$ is called a *basis* of $V$ if $\mathrm{Span}(S)=V$ and $S$ is linearly independent.

#### Dimension

**Theorem:** Every vector space has a basis. 

**Proof:** This requires Zorn's Lemma.  If $S_{1}\subset S_{2}\subset\cdots$ is an ascending sequence of linearly independent sets, their union is also linearly independent (because any linear relation would only involve finitely many vectors so would hold at some finite level of the chain). Therefore the linearly independent subsets of $V$ form a partially ordered set in which every ascending chain has a maximal element.  It follows that there is a maximal linearly independent set $B$ in $V$.  

Now choose any $v\in V$.  If $v$ is not in the span of $B$, then $B\cap \{v\}$ would be linearly independent, contradicting maximality of $B$.

Hence $B$ spans $V$ and is therefore a basis.

**Theorem:** Any two bases of a vector space $V$ have the same cardinality.  

**Proof:** Suppose that $X$ and $Y$ are bases of the same vector space $V$.
Each $x\in X$ is a *finite* linear combination of elements of $Y$.  This means
there is a surjective finite-to-one map from $Y$ to $X$.  The surjectivity tells
us that $|Y|\ge |X|$.  On the other hand, a theorem in cardinal arithmetic (Hessenberg's
Theorem) says that if $X$ is infinite and $Y\to X$ is finite-to-one then $|Y|\le |X|$.
Then The Cantor-Bernstein theorem says that $X$ and $Y$ have the same cardinality.
)
We will establish the fact that any two finite bases of $V$ have the same number of elements a little later.

**Definition:** The dimension of $V$ is the cardinality of any basis of $V$.

If $V$ has a finite basis, it is said to be
finite-dimensional; otherwise it is infinite-dimensional.




