---
title: Sums, Quotients, and Complexes
---

\newcommand{\F}{\mathbf{F}}
\newcommand{\dim}{\mathrm{dim}}
\newcommand{\rank}{\mathrm{rank}}
\newcommand{\nullity}{\mathrm{nullity}}
\newcommand{\columns}{\mathrm{columns}}

### Sums and Quotients

Let $V$ and $W$ be vector spaces over a field $\F$.  

The *direct sum* of $V$ and $W$ is the
set of pairs
$$
V\oplus W = \{(v,w) : v\in V, w\in W \} 
$$

This is a vector space with the operations
$$
(v,w) + (v',w') = (v+v', w+w').
$$

and 

$$
a(v,w) = (av,aw).
$$

One can define the direct sum of a finite family $\{V_{i}\}_{i=1}^{m}$ of vector spaces to be the set of sequences

$$
(v_1,\ldots, v_m)
$$

where $v_{i}\in V_{i}$.

Again the operations are componentwise. 

Infinite direct sums are also defined.  Given an index set $I$ and a family $\{V_{i}\}_{i\in I}$ of vector spaces, then the direct sum 
$$
\oplus_{i\in I}V_{i}
$$

is the set of functions $f:I\to \bigcup_{i\in I}V_{i}$ such that $f(i)\in V_{i}$
and $f(i)=0$ for all but finitely many $i\in I$.

The field  $\F$ is a one-dimensional vector space over itself. 
The vector space $\F^{n}$ is just $\oplus_{i=1}^{n}\F$. 

Note that $V$ and $W$ are subspaces of $V\oplus W$ by identifying
$V$ with the pairs $(v,0)$ and $W$ with the pairs $(0,w)$.  The intersection of these two subspaces is $0=(0,0)$. 

**Proposition:** If $V$ and $W$ are finite dimensional of dimension $n$ and $m$ respectively, then $V\oplus W$ is finite dimensional of dimension $n+m$.

In fact if $v_1,\ldots, v_n$ is a basis for $V$, and $w_1,\ldots, w_m$ is a basis for $W$, then $(v_1,0),\ldots, (v_n,0),(0,w_1),\ldots, (0,w_m)$
is a basis for $V\oplus W$.  

They span since 
$$
(v,w) = (\sum a_{i}v_{i}, \sum b_{i}w_{i}) = \sum a_{i}(v_{i},0) + \sum b_{i}(0,w_{i}).
$$

They are independent since if 
$$
(\sum a_{i}v_{i},\sum b_{i}w_{i})=(0,0)
$$

then all the $a_{i}$ and $b_{i}$ are zero by independence of the $v$'s and $w$'s.


#### Subspace sums and internal direct sums

Let $V$ be a vector space and let $U$ and $W$ be subspaces of $V$.
The *sum* of $U$ and $W$ is the set
$$
U+W = \{u+w : u\in U, w\in W\} 
$$

This is a subspace of $V$.  

- It is the smallest subspace of $V$ containing both $W$ and $U$. 
- If $u_1,\ldots, u_n$ span $U$ and $w_1,\ldots, w_k$ span $W$ then
the union $u_1,\ldots, u_n, w_1,\ldots, w_k$ span $U+W$. 
- the dimension of $U+W$ is at most $\mathrm{dim}(U)+\mathrm{dim}(W)$.
It can certainly be smaller (suppose $U=W$ for example).

##### Algorithm to compute a basis for $U+W$.

1. Choose a basis for $V$ and take spanning sets as above for $U$ and $W$.
Create a matrix $A$ whose columns are the $u_i$ and $w_j$ written in the chosen basis for $V$.

2. Put the matrix $A$ in rref yielding $A'$. 

3.  The columns of $A$ corresponding to the pivot columns of $A'$ are a basis for $U+W$.

4.  The basis constructed in this way will be a subset of the union of the $u_{i}$ and $w_{j}$.

#### Internal direct sum

If $U$ and $W$ are subsets of $V$ such that every element of $x\in U+W$
has a *unique* representation  $x=u+w$ with $u\in U$ and $w\in W$,
then $U+W$ is an (internal) direct sum and $U+W$ is isomorphic to $U\oplus W$. 

**Proposition:** $U+W$ is a direct sum if and only if either of the following hold:

a. $U\cap W=0$.
b. $\mathrm{dim}(U)+\mathrm{dim}(W)=\mathrm{dim}(U+W)$.

Suppose that $u+w=u'+w'$ for $u,u'\in U$ and $w,w'\in W$. Then
$(u-u') = (w'-w)$.  The left side is in $U$, and the right side is in $W$,
so both $u-u'$ and $w'-w$ are in $U\cap W$.  If $U\cap W=0$ this implies that $u=u'$ and $w=w'$ so the representation is unique.  If not, then
choose $z\in U\cap W$ with $z\not=0$ and we have $u+w = (u+z) + (w-z)$
so the representation is not unique. 

For the second, choose  bases $u_1,\ldots, u_n$ of $U$ and $w_1,\ldots, w_k$ of $W$.  Together these span $U+W$.  On the other hand if there is a non trivial linear relation among them, we would have
$$
\sum a_{i}u_{i} +\sum b_{j}w_{j}=0.
$$
Since the $u_i$ and $w_j$ are independent, any such relation must involve a mix of both $u_i$ and $w_j$ vectors, and so represents an element of $U\cap W$.  

So the formula above is just the rank plus nullity = columns equation for the matrix $A$.
At least one $a_{i}$ and one $b_{j}$ must be nonzero (since the $u$'s and $w$'s are separately independent).  This gives us a non-zero vector
$$
\sum a_{i}u_{i} = -\sum b_{j}w_{j}
$$
in $U\cap W$.   

Thus they are independent and (b) follows.  Conversely, if we have the relation on dimensions, these $u_i$ and $w_{j}$ must be independent. 
A nonzero element of $U\cap W$ would give a non-trivial equation 
$$
\sum a_{i}u_{i} = \sum b_{j} w_{j}
$$

which would imply the $u_i$ and $v_j$ are dependent and thus the dimension of $U+W$ is smaller than $n+k$.

One can improve this result a bit to obtain this formula.

**Proposition:** Given subspaces $U$ and $W$ of $V$ we have
$$
\begin{aligned}
\mathrm{dim}(U+W) &= \mathrm{dim}(U\oplus W)-\mathrm{dim}(U\cap W) \\
&= \mathrm{dim}(U)+\mathrm{dim}(W)-\mathrm{dim}(U\cap W)
\end{aligned}
$$

This follows from our algorithm above.  Make a matrix $A$ whose columns are the basis elements $u_i$ and $w_j$ for $U$ and $W$ respectively written
in some basis for $V$.  The rank of $A$ is dimension of the span of the columns of $A$,
which is the dimension of $U+W$.  Let $y^{(k)}$ be a basis for the null space of $A$.  Each element
of this basis gives
a relation
$$
\sum_{i=1}^{\dim(U)} y^{(k)}_{i}u_{i} + \sum_{j=1}^{\dim(W)}y^{(k)}_{\dim(U)+j}w_{j}=0.
$$
We can read this relation as:
$$
\sum_{i=1}^{\dim(U)} y^{(k)}_{i}u_{i} = - \sum_{j=1}^{\dim(W)}y^{(k)}_{\dim(U)+j}w_{j}.
$$
Since the $u_{i}$ and $w_{j}$ are linearly independent, it must be the case that at least one of
the $y_{i}$ on the left, and one on the right, are non-zero.
Therefore each element $y^{(k)}$ of the null space of $A$ yields an
$$
h_{k}=\sum_{i=1}^{\dim(U)} y^{(k)}_{i}u_{i}
$$
that is a non-zero element that belongs to $U\cap W$.

We claim that the $h_{k}$ are a basis for $U\cap W$.  The spanning property comes because
if $h\in U\cap W$, then writing $h=\sum a_{i}u_{i}=\sum b_{j}w_{j}$ in terms of the $u_{i}$ and in terms of the $w_{j}$ gives
a relation
$$
\sum a_{i}u_{i}-\sum b_{j}w_{j}=0
$$
which in turn produces an element of the null space of $A$.  Writing this in terms of the $y^{(k)}$
in turn yields a linear expression for $h$ in terms of the $h_{k}$.

To see the independence of the $h_{k}$, suppose
$$
\sum_{k} a_{k}h_{k} = \sum_{k}\sum_{i} a_{k}y^{(k)}_{i}u_{i} = 0.
$$
The independence of the $u_{i}$ means that, for each $i=1,\ldots,\dim(U)$,  $\sum_{k} a_{k}y^{(k)}_{i}=0$.  A similar expression using the $w_{j}$ gives
$$
\sum_{k} a_{k}y^{(k)}_{\dim(U)+j}=0
$$
for all $j=1,\ldots, \dim(W)$.  Putting these together gives a relation among the $y^{(k)}$,
which are independent, so all $a_{k}$ must be zero.

We've shown that the rank of $A$ is $\dim(U+W)$, the number of columns of $A$ is $\dim(U)+\dim(W)$,
and the nullity of $A$ is $\dim(U\cap W)$, so the desired formula is the known formula
$$
\rank(A)+\nullity(A) = \columns(A)
$$

$$
\begin{aligned}
\mathrm{dim}(U+W) &= \mathrm{dim}(U\oplus W)-\mathrm{dim}(U\cap W) \\
&= \mathrm{dim}(U)+\mathrm{dim}(W)-\mathrm{dim}(U\cap W)
\end{aligned}
$$


### Quotient Spaces



An *equivalence relation* on a set $X$ is a
relation $x\sim y$ between any two elements of $X$ with the properties that:

1. $x\sim x$ for all $x\in X$.
2. If $x\sim y$, then $y\sim x$ for all $x,y\in X$.
3. If $x\sim y$ and $y\sim z$ then $x\sim z$ for all $x,y,z\in X$.

An equivalence relation partitions $X$ into equivalence classes.  An equivalence class
$$
[x] =\{y\in X : y\sim x\}
$$

Every element of $X$ belongs to exactly one
class.  Put another way, given two elements
$x$ and $y$ in $X$, either $[x]=[y]$ or 
$[x]\cap [y]=\emptyset$.

To see this, clearly $x\in [x]$.  Suppose
$a\in [x]\cap [y]$.  Then $a\sim x$ and $a\sim y$ so $y\sim x$.  Therefore $y\in [x]$. If $u\sim y$, then $u\sim x$ so $u\in [x]$.
Therefore $[y]\subset [x]$.  The same argument
run "the other way" shows $[x]\subset [y]$.
So $[x]\cap [y]\not=\emptyset$ implies $[x]=[y]$.

Now suppose $V$ is a vector space over $F$ and $W$ is a subspace of $V$.  Define an equivalence relation on $V$ by setting
$$
x\sim y \iff x-y\in W.
$$

The set of equivalence classes $[x]$ is called the *quotient space* $V/W$.

In fact $V/W$ is a vector space over $F$.
We define 
$$
[x]+[y] = [x+y]
$$
and 
$$
a[x]=[ax]
$$

We have to verify that these operations are well-defined and that they satisfy all the vector space axioms.

To see that addition is well-defined, suppose
$[x]=[a]$ and $[y]=[b]$.  Then we claim
$$
[x+y]=[a+b]
$$
This is because
$$
(a+b)-(x+y)=(a-x)+(b-y)\in W.
$$

Similarly if $[x]=[y]$ then $x-y\in W$
so $ax-ay\in W$ and therefore $[ax]=[ay]$.

Checking all the axioms is tedious but
straightforward.  For example,
$$
\begin{aligned}
a([x]+[y])&=a([x+y])=[a(x+y)] \\
&=[ax+ay]=[ax]+[ay]=a[x]+a[y]
\end{aligned}
$$

**Proposition:** Suppose that $V$ is finite dimensional and $W\subset V$.  Then $\dim(V/W)=\dim(V)-\dim(W)$.

**Proof:** The map $f:V\to V/W$ defined by $f(v)=[v]$ is an onto linear map with nullspace exactly $W$.  Linearity:

- $f(x+y)=[x+y]=[x]+[y]=f(x)+f(y)$
- $f(ax) = [ax] = a[x] = af(x)$

The fact that the map is onto is because if 
$[v]\in V/W$ then $f(v)=[v]$.

Finally, the nullspace of $f$ is the set of $v$ such that $f(v)=[v]=[0]$.  But $[v]=[0]$
if and only if $v\in W$.

Thus the dimension relation follows from the rank/nullity theorem for the linear map $f$.

**Proposition:** Let $f:V\to W$ be a linear map and suppose $H\subset V$
is contained in the kernel of $f$.  Then there is a unique linear map 
$\overline{f}:V/H\to W$ such that $\overline{f}([v])=f(v)$ for all
$v\in V$.

Proof: The map $\overline{f}$ defined by $\overline{f}([v])=f(v)$ has
the desired property and
is well-defined because if $[v]=[x]$ then $v-x\in H$.  Since $H$
is contained in the kernel of $f$, this means that $f(v-x)=0$ so $f(v)=f(x)$.

The existence of the map $\overline{f}$ is called *the universal mapping property of the quotient $V/H$*.

One can show that the subspaces of $V/H$ correspond exactly to the subspaces of $V$ containing $H$. 

### Complexes

**Definition:** A complex of vector spaces is a sequence of vector spaces
$W^{i}$ connected by linear maps $d_{i}$ 
$$
\cdots \to \cdots \to W^{i}\stackrel{\to}{d_{i}} W^{i+1} \stackrel{\to}{d_{i+1}}W^{i+2}\to\cdots
$$

with the property that $d_{i+1}d_{i}=0$ for all $i$. 

The complex is bounded if all but finitely many $W^{i}$ are zero.

Let $Z^{i}\subset W^{i}$ be the null space of $d_{i}$ and let
$B^{i}\subset W^{i}$ be the image $d_{i-1}(W_{i-1})\subset W^{i}$. 

The elements of $Z^{i}$ are called cocycles and those of $B^{i}$
are called coboundaries.

The vector space $Z^{i}/B_{i}$ is the $i^{th}$ cohomology 
$H^{i}(W^{\cdot})$ of the complex.

Suppose the complex is bounded and all $W^{i}$ are finite dimensional.
The sum
$$
\chi(W^{\cdot})=\sum_{-\infty}^{\infty} (-1)^{i}\dim(W^{i})
$$

is called the Euler characteristic of the complex.

**Proposition:** We have
$$
\chi(W^{\cdot})=\sum_{-\infty}^{\infty} (-1)^{i}\dim H^{i}(W^{\cdot})
$$

**Proof:** Notice that $\dim(B^{i+1})=\dim(W^{i})-\dim(Z^{i})$ since
the image of $d^{i}$ is $B^{i+1}$ and its kernel is $Z^{i}$. 
So:
$$
\sum (-1)^{i}\dim(W^{i}) = \sum (-1)^{i}(\dim(B^{i+1})+\dim(Z^{i})).
$$
Now
$$
\sum (-1)^{i}(\dim(B^{i+1})+\dim(Z^{i}))=\sum (-1)^{i}(\dim(Z^{i})-\dim(B^{i}))
$$

which is the alternating sum of the dimensions of the $H^{i}(W^{\cdot})$.
